# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.TextField(max_length=40)),
                ('kid_photo', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Santa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('santa_name', models.TextField(max_length=40)),
                ('santa_photo_url', models.TextField(max_length=200)),
            ],
        ),
    ]
